flowchart TD
    Start(["开始"]) --> OS系统信息录入
    OS系统信息录入 --> 项目申报与立项
    项目申报与立项 --> 合同签订用印
    合同签订用印 --> End(["结束"])
    
    OS系统信息录入 --> 市场信息在OS系统中录入
    OS系统信息录入 --> 培训方案协议草案
    
    项目申报与立项 --> OS系统申报培训项目
    项目申报与立项 --> 分管领导审批1
    分管领导审批1 --> 审批1
    审批1 --> 立项
    
    合同签订用印 --> 签订培训采购协议
    合同签订用印 --> 分管领导审批2
    分管领导审批2 --> 审批2
    审批2 --> 用印管理流程