flowchart TD
    Start(["开始"])
    End(["结束"])
    A["提出申请"]
    B["对市场需求和经济效益作预测分析，填写《苏州大学专利申请前评估准许表》"]
    C["学院组织进行专利申请前评估"]
    D["材料备案，保留原件"]
    E["如与外单位共同申请，需提供共享证明"]
    F{"是否涉密"}
    G["涉密审查"]
    H["申请国防专利"]
    I["委托中标知识产权代理服务机构办理（与外单位共同申请的除外）"]

    Start --> A
    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F -- 是 --> G
    G --> H
    H --> End
    F -- 否 --> I
    I --> End