flowchart TD
    A([开始]) --> B[根据上级主管部门通知发布结题/验收通知]
    B --> C[按主管部门要求填写验收申请表、报告、项目经费决算表、研发工作总结等材料]
    C --> D[按照要求审核经费决算表并盖章（如果需要）]
    D --> E[汇总验收材料]
    E --> F[审核]
    F --> G[完成后续工作。邀请验收专家、PPT汇报、填写验收证书、验收材料归档等]
    G --> H([结束])