flowchart TD
    Start((开始))
    A1[学院联系人与捐赠方商洽，明确捐赠意向，并联系学院对外合作办公室]
    A2[捐赠项目可行性论证]
    A3[学院对外合作办公室与校基金会、捐赠方会商捐赠协议内容]
    A4[按照基金会捐赠协议规范格式拟定捐赠协议]
    A5[审批]
    A6[审核]
    A7{受赠金额在500万元（不含）以内}
    A8[基金法定代表人或其授权人签署]
    A9[基金法定代表人签署]
    A10[捐赠方确认捐赠协议内容]
    A11[基金会法定代表人（理事长）或其授权人签字，并加盖基金会公章]
    A12[学院对外合作办公室履行合同并实施捐赠立项<br>《捐赠项目立项表》]
    A13[审批并盖章]
    A14[审核确认]
    A15[出具收款通知书、立项表、捐赠协议等材料]
    A16[开具捐赠收据]
    A17[财务处入账]
    A18[将捐赠收据、盖章后的捐赠协议等材料交付捐赠方]
    End((结束))

    Start --> A1
    A1 --> A2
    A2 --> A3
    A3 --> A4
    A4 --> A5
    A5 --> A6
    A6 --> A7
    A7 -- 是 --> A8
    A7 -- 否 --> A9
    A8 --> A10
    A9 --> A10
    A10 --> A11
    A11 --> A12
    A12 --> A13
    A13 --> A14
    A14 --> A15
    A15 --> A16
    A16 --> A17
    A17 --> A18
    A18 --> End