flowchart TD
    Start(["开始"]) --> A[接到上级通知设立专项]
    A --> B[接到通知编制预算，与学科处会同制定]
    B --> C[制定绩效目标预算编制流程]
    C --> D[审批]
    D --> E[审批]
    E --> F[审批]
    F --> G[审核]
    G --> H[收到当年度学科经费]
    H --> I[按项目任务书建设]
    I --> J[组织实施绩效评价]
    J --> K[对学科建设项目进行自评 《自评报告》、《专项资金绩效目标表》]
    K --> L[审核]
    L --> M[反馈评价意见]
    M --> End(["结束"])