flowchart TD
    Start((开始)) --> A[提出维修申请]
    A --> B[综合办公室对维修项目进行评估确定金额]
    B --> C{维修金额判断}
    C -->|1000元以下| D[零星维修系统申请] --> End((结束))
    C -->|1000元-5万元| E{是否从单位自筹经费列支？}
    E -->|是| F[院系行文申请，苏州大学维修改造项目立项申请表] --> G[审批] --> H[审批] --> I[审批] --> End
    E -->|否| J[审批] --> K[审批] --> End((结束))