flowchart TD
    Start((开始)) --> A[对学生进行测评]
    A --> B[申请人]
    B --> C{提交申请材料<br>（相关证书复印件或证明原件）}
    C --> D[学生工作办公室]
    D --> E[对学生进行测评]
    E --> F[初审]
    F --> G[学院分管领导]
    G --> H[进行资质审核和评审，公示初评名单]
    H --> I{是否有异议}
    I -->|是| J[核实处理] --> G
    I -->|否| K[学院党政联席会议]
    K --> L[审核初评结果，签署意见]
    L --> M[校学生工作处]
    M --> N[审核]
    N --> O[审核]
    O --> P[公示]
    P --> Q[奖励助学金工作领导小组]
    Q --> R[审定，公布正式名单]
    R --> End((结束))