flowchart TD
    Start(["开始"]) --> A[在OS上提出开卡申请]
    A --> B[审批]
    B --> C[打印开卡证明]
    C --> D[向财务处借款]
    D --> E[开卡]
    E --> F[培训结束后，打印销卡证明]
    F --> G[销卡]
    G --> H[发起内部转账申请，《苏州大学内部转账通知单》]
    H --> I[审批]
    I --> J[财务处审核并内转]
    J --> End(["结束"])