flowchart TD
    A([开始]) --> B[维修完成组织验收，申请人填写《苏州大学工程验收报告书》]
    B --> C{合同金额是否小于1万元（不含）}
    C -- 是 --> D[资产管理员组织验收]
    C -- 否 --> E{合同金额是否在1万元（含）-5万元（不含）之间}
    E -- 是 --> F[资产管理员和归口部门共同组织验收]
    E -- 否 --> G[归口部门组织初步验收]
    G --> H[归口部门组织施工单位、对应的行政部门实施正式验收]
    D --> I[项目责任人和监理单位（如有）签署竣工验收意见]
    F --> I
    H --> I
    I --> J([结束])