flowchart TD
    Start(["开始"]) --> A[培训班开班管理]
    A --> B[培训项目结项]
    B --> C[OS系统申请费用结算 《苏州大学培训经费结算表》]
    C --> D[审批]
    D --> E[审核]
    E --> F[申请开票流程]
    F --> G[催款及到款认领]
    E --> H[各项费用支出流程]
    B --> I[培训项目自评]
    I --> J[监督管理]
    J --> End(["结束"])