flowchart TD
    Start([开始]) --> A[提出转化申请]
    A --> B{是否与转让方存在利益关系？}
    B -->|是| C[由学校认可的第三方知识产权专门评估机构进行价值评估，确定转化价格。]
    C --> D[签署承诺书]
    D --> E{是否协议定价？}
    E -->|是| F[合同草拟]
    F --> G[学校OA系统发起合同用印申请]
    G --> H[合同签订，并将扫描件上传至知识产权管理系统]
    H --> I[实施转化]
    G --> J[审核]
    J --> End1([结束])
    E -->|否| K[审核]
    K --> L[在科学技术研究院网站公示科技成果和转化信息及交易价格，公示期为**天**]
    L --> M{无异议？}
    M -->|是| N[审核]
    N --> End2([结束])
    M -->|否| O[公示有异议：组织不少于3人的行业专家进行论证]
    O --> P[反馈给异议者]
    P --> Q[审核]
    Q --> End3([结束])
    B -->|否| R[签署审核意见并用印]
    R --> S{金额≥300万元？}
    S -->|是| T[审批]
    T --> U[审核]
    U --> V[审批]
    V --> W[审批]
    W --> End4([结束])
    S -->|否| X[审批]
    X --> Y[审核]
    Y --> Z[审批]
    Z --> AA[审批]
    AA --> End5([结束])