flowchart TD
    Start([开始]) --> A[学生工作办公室对学生进行测评]
    A --> B[申请人提交申请材料（相关证书复印件或证明原件）]
    B --> C[学生工作办公室初审]
    C --> D[学生工作办公室进行资质审核和评审，公示初评名单]
    D --> E{是否有异议}
    E -->|是| F[核实处理] --> D
    E -->|否| G[学院分管领导审核初评结果，签署意见]
    G --> H[学院党政联席会议审核]
    H --> I[校党委研究生工作部审核]
    I --> J[公示]
    J --> K[奖励助学金工作领导小组审定，公布正式名单]
    K --> End([结束])