flowchart TD
    Start(["开始"]):::ellipse
    End(["结束"]):::ellipse
    A[科学技术研究院根据上级主管部门通知发布结题/验收通知]
    B[学院科研项目经办人按主管部门要求填写验收申请表、报告、项目经费决算表、研发工作总结等材料]
    C{财务处/审计处按照要求审核经费决算表并盖章（如果需要）}
    D[学院科研项目经办人汇总验收材料]
    E[科学技术研究院审核]
    F[学院科研项目经办人完成后续工作。邀请验收专家、PPT汇报、填写验收证书、验收材料归档等]

    Start --> A --> B --> C --> D --> E --> F --> End

    classDef ellipse fill:#f9f,stroke:#333,stroke-width:2px;