flowchart TD
    A((开始)) --> B(申请人提出申请)
    B --> C(项目负责人审批)
    C --> D(分管领导审批)
    D --> E(申请人登录智能财务平台提出报销申请)
    E --> F(提交《苏州大学差旅预约单》及相关证明文件)
    F --> G(项目负责人审批)
    G --> H{判断是否属于项目负责人本人差旅费}
    H -->|是| I(分管领导审批)
    H -->|否| J(财务处审核并支付)
    I --> J
    J --> K((结束))