flowchart TD
    Start(["开始"]) --> P01["科学技术研究院\n发布申报通知"]
    P01 --> P02["学院科研项目经办人\n准备申报材料"]
    P02 --> P03["学院分管领导\n分管领导审批"]
    P03 --> P04["科学技术研究院\n评审，上报"]
    P04 --> P05["收到上级主管部门批文"]
    P05 --> P06["填报和递交项目预算书、项目合同书、任务书、计划书"]
    P06 --> P07["提交上级主管部门审核通过后予以立项"]
    P07 --> P08["签订项目合同书，并在学校科技管理信息系统录入项目信息及预算并上传批文、任务书/计划书合同书（含预算）"]
    P08 --> P09["审批"]
    P09 --> P10["审核并立项"]
    P10 --> End(["结束"])