flowchart TD
    Start(["开始"]) --> A[学科建设与发展规划处接到上级通知设立专项]
    A --> B[学科秘书接到通知编制预算，与学科处会同制定]
    B --> C[学科秘书制定绩效目标预算编制流程]
    C --> D[学院项目负责人审批]
    D --> E[学院负责人/院分管领导审批]
    E --> F[学科建设与发展规划处审批]
    F --> G[财务处审核]
    G --> H[学科秘书收到当年度学科经费]
    H --> I[学科秘书按项目任务书建设]
    I --> J[学科建设与发展规划处组织实施绩效评价]
    J --> K[学科秘书对学科建设项目进行自评 《自评报告》、《专项资金绩效目标表》]
    K --> L[学科建设与发展规划处审核]
    L --> M[学科建设与发展规划处反馈评价意见]
    M --> End(["结束"])