flowchart TD
    Start(["开始"]) --> A[经办人填写《红楼会议中心会场使用登记单》]
    A --> B[学院（项目）负责人审批]
    B --> C[发出转账通知，《苏州大学内部转账通知单》]
    C --> D[发起转账申请]
    D --> E[学院（项目）负责人审批]
    E --> F[财务处审核并支付]
    F --> End(["结束"])