flowchart TD
    开始((开始))
    申请人登录师生网上事务中心提前在线申请
    填写基本信息和本次出访相关信息上传所需附件
    是否处级干部{是否处级干部？}
    组织部纪委审批[组织部、纪委审批]
    学院对外合作办公室审批[学院对外合作办公室审批]
    学院分管领导审批[学院分管领导审批]
    出入境服务中心受理公示及OA行文办理[出入境服务中心受理、公示及OA行文办理]
    校长办公室审核并形成红头文件报江苏省人民政府外事办公室审批[校长办公室审核，并形成红头文件报江苏省人民政府外事办公室审批]
    出入境服务中心办理因公护照因公签证[出入境服务中心办理因公护照、因公签证]
    申请人办理相关手续签订协议如有[申请人办理相关手续，签订协议（如有）]
    出国[出国]
    回国[回国]
    到本学院报到提交总结反馈报告[1个月到本学院报到、提交总结反馈报告]
    学院对外合作办公室公示[学院对外合作办公室公示]
    出入境服务中心收回因公普通护照[出入境服务中心收回因公普通护照]
    财务处费用报销[财务处费用报销]
    结束((结束))

    开始 --> 申请人登录师生网上事务中心提前在线申请
    申请人登录师生网上事务中心提前在线申请 --> 填写基本信息和本次出访相关信息上传所需附件
    填写基本信息和本次出访相关信息上传所需附件 --> 是否处级干部
    是否处级干部 -- 是 --> 组织部纪委审批
    是否处级干部 -- 否 --> 学院对外合作办公室审批
    组织部纪委审批 --> 出入境服务中心受理公示及OA行文办理
    学院对外合作办公室审批 --> 学院分管领导审批
    学院分管领导审批 --> 出入境服务中心受理公示及OA行文办理
    出入境服务中心受理公示及OA行文办理 --> 校长办公室审核并形成红头文件报江苏省人民政府外事办公室审批
    校长办公室审核并形成红头文件报江苏省人民政府外事办公室审批 --> 出入境服务中心办理因公护照因公签证
    出入境服务中心办理因公护照因公签证 --> 申请人办理相关手续签订协议如有
    申请人办理相关手续签订协议如有 --> 出国
    出国 --> 回国
    回国 --> 到本学院报到提交总结反馈报告
    到本学院报到提交总结反馈报告 --> 学院对外合作办公室公示
    学院对外合作办公室公示 --> 出入境服务中心收回因公普通护照
    出入境服务中心收回因公普通护照 --> 财务处费用报销
    财务处费用报销 --> 结束