flowchart TD
    Start(["开始"]) --> A["培训班开班管理"]
    A --> B["培训项目结项"]
    B --> C["申请费用结算"]
    C --> D["学院分管领导审批"]
    D --> E["继续教育学院审核"]
    E --> F{"分支"}
    F --> G["申请开票流程"]
    G --> H["催款及到款认领"]
    F --> I["各项费用支出流程"]
    B --> J["培训项目自评"]
    J --> K["继续教育学院监督"]
    K --> End(["结束"])
    H --> End
    I --> End