flowchart TD
    Start(["开始"]) --> A[项目负责人草拟合同]
    A --> B{是否按合同模板填写}
    B -->|是| C{项目金额是否超过300万}
    C -->|是| D[法律事务办公室审核]
    C -->|否| E[产业技术研究院审核]
    B -->|否| F[OA系统申请合同审批]
    D --> G[项目负责人修改合同]
    G --> E
    F --> E
    E --> H[项目负责人签订合同]
    H --> I[产业技术研究院审核并盖章，备案合同原件]
    I --> J[项目负责人系统立项申请]
    J --> K[产业技术研究院审核通过]
    K --> End(["结束"])