flowchart TD
    A[开始] --> B(成立筹备工作组，由学院党委负责人任组长)
    B --> C(征集议题，整理提案)
    C --> D{提案是否通过}
    D -->|否| E(提案未获通过的反馈给提案人，结束)
    D -->|是| F(拟定大会日程和议程、确定中心议题)
    F --> G(审核)
    G --> H(审核)
    H --> I(预备会议)
    I --> J(正式会议)
    J --> K{半数以上赞成有效}
    K -->|是| L(审议通过)
    L --> M[结束]
    K -->|否| M[结束]