flowchart TD
    A(["开始"]) --> B(上级主管部门发布指南，平台管理办公室发布申报通知)
    B --> C(科研秘书通知科研人员，组织申报)
    C --> D(负责人与平台管理办公室沟通申报意向，确认申报细节)
    D --> E(负责人准备申报材料)
    E --> F(科研秘书进行形式审查，组织单位内部预评审（如有需要）)
    F --> G(将申报材料报送平台管理办公室)
    G --> H(审批)
    H --> I(平台管理办公室对申报材料进行形式审查，组织校内评审（如有需要）)
    I --> J(汇总申报材料用印后上报主管部门)
    J --> K(["结束"])