flowchart TD
    Start([开始])
    End([结束])
    A[提前6个月申请，上传相关材料]
    B[OA材料接收]
    C[OA审批]
    D[审核]
    E[审核预算]
    F[是否处级以上干部]
    G[审批]
    H[是否出国6个月以上]
    I[备案]
    J[公示]
    K[办理相关手续、联系担保人、签订协议]
    L[缴纳保证金3万元<br>开立收据<br>备案]
    M[学院谈话]
    N[行前培训]
    O[出国（境）]
    P[出国期间工作汇报]
    Q[回国]
    R[一个月内持护照、签证等材料到学院和人力资源处报到<br>《苏州大学公派出国（境）教师回国考核表》]
    S[考核、报到]
    T[审批]
    U[备案]
    V[报销费用并退保证金]

    Start --> A --> B --> C --> D --> E --> F
    F --是--> G --> J
    F --否--> H
    H --是--> I --> J
    H --否--> J
    J --> K --> H
    H --是--> L --> M
    H --否--> M
    M --> N --> O --> P --> Q --> R --> S --> T --> U --> V --> End