flowchart TD
    Start(["开始"]) --> A["科学技术研究院发布申报通知"]
    A --> B["学院科研项目经办人准备申报材料"]
    B --> C["学院分管领导审批"]
    C --> D["科学技术研究院评审，上报"]
    D --> E["科学技术研究院收到上级主管部门批文"]
    E --> F["学院科研项目经办人填报和递交项目预算书、项目合同书、任务书、计划书"]
    F --> G["科学技术研究院提交上级主管部门审核通过后予以立项"]
    G --> H["学院科研项目经办人签订项目合同书，并在学校科技管理信息系统录入项目信息及预算并上传批文、任务书/计划书合同书（含预算）"]
    H --> I["学院分管领导审批"]
    I --> J["科学技术研究院审核并立项"]
    J --> End(["结束"])