flowchart TD
    A[开始] --> B[学生工作办公室对学生进行测评]
    B --> C[申请人提交申请材料（相关证书复印件或证明原件）]
    C --> D[学生工作办公室初审]
    D --> E[学生工作办公室进行资质审核和评审，公示初评名单]
    E --> F{是否有异议}
    F -->|是| G[核实处理] --> E
    F -->|否| H[学院分管领导审核初评结果，签署意见]
    H --> I[学院党政联席会议审核]
    I --> J[校学生工作处审核]
    J --> K[公示]
    K --> L[奖励助学金工作领导小组审定，公布正式名单]
    L --> M[结束]