flowchart TD
    A[("开始")] --> B[申请人通过智能财务平台提交申请，根据学院福利费管理制度规定的金额执行]
    B --> C[学院分管领导审批]
    C --> D{判断是否向学校申请困难补助？}
    D -->|否| E[跳过“审批”步骤]
    D -->|是| F[人力资源处审批]
    E --> G[财务处审核并支付]
    F --> G
    G --> H[("结束")]