flowchart TD
    Start(["开始"]) --> A[提交材料，通过邮箱申请]
    A --> B[评审小组审核评定]
    B --> C[审批]
    C --> D[告知反馈]
    D --> E[在学院网站公布奖教金名单]
    E --> F[编制院设奖教金发放表]
    F --> G[学院负责人审批]
    G --> H[审批]
    H --> I[财务处支付奖学金]
    I --> End(["结束"])