flowchart TD
    Start((开始))
    End((结束))
    A[申请人提出用车申请，《用车审批单》]
    B{是否定点服务供应商车辆}
    C[审批]
    D{单次金额判断}
    E[进入服务采购流程]
    F[订立合同]
    G[审批金额年度累计不超过5000元]
    H[登录智能财务平台，提出报销申请，提交《苏州大学差旅预约单》及相关证明文件]
    I[审批]
    J[审核并支付]

    Start --> A
    A --> B
    B -- 是 --> C
    B -- 否 --> D
    D -- 5万元及以上 --> E --> C --> C
    D -- 3万元（含）至5万元（不含） --> F --> C --> C
    D -- 1000元（含）至3万元（不含） --> C --> C
    D -- 1000元以下 --> G --> C
    C --> H
    H --> I
    I --> J
    J --> End