flowchart TD
    Start(["开始"]) --> A[提出报销申请]
    A --> B{是否有新增人员}
    B -->|是| C[维护新增人员信息]
    C --> D[财务处审核]
    D --> E[申请人登录智能财务平台（酬金管理模块）进行申请]
    B -->|否| E
    E --> F[《苏州大学酬金申报预约单》]
    F --> G[项目负责人审批]
    G --> H{是否为项目负责人本人酬金}
    H -->|是| I[分管领导审批]
    H -->|否| J[财务处审核并支付]
    I --> J
    J --> End(["结束"])