flowchart TD
    Start(["开始"]) --> A[保管人核实材料情况（资产名称、型号、单价、使用方向、供应商、存放地、保管人）]
    A --> B[保管人通过苏州大学国有资产管理服务平台-低值耐用资产管理]
    B --> C[资产管理员审核]
    C --> D[国资处审核]
    D -->|是| E[生成资产入库单]
    D -->|否| F[保管人修改信息]
    F --> G[资产管理员审核，验收人签字的发票或集中采购发货单等相关材料扫描件]
    G --> C
    E --> End(["结束"])