flowchart TD
    Start(["开始"]) --> Node1("培训班开班管理")
    Node1 --> Node2("培训项目结项")
    Node2 --> Node3("OS系统申请费用结算 《苏州大学培训经费结算表》")
    Node3 --> Node4("学院分管领导审批")
    Node4 --> Node5("继续教育学院审核")
    Node5 --> Node6("申请开票流程")
    Node6 --> Node7("催款及到款认领")
    Node5 --> Node8("各项费用支出流程")
    Node2 --> Node9("培训项目自评")
    Node9 --> Node10("继续教育学院监督管理")
    Node10 --> End(["结束"])