flowchart TD
    Start(["开始"]) --> A[申请人提前6个月申请，上传相关材料]
    A --> B[学院综合办公室OA材料接收]
    B --> C[学院负责人OA审批]
    C --> D[国际合作交流处审核]
    D --> E[财务处审核预算]
    E --> F[人力资源处审核]
    F --> G{是否处级以上干部}
    G -->|是| H[党委组织部审批] --> I[人力资源处公示]
    G -->|否| J{是否出国6个月以上}
    J -->|是| K[党委组织部备案] --> I
    J -->|否| I
    I --> L[申请人办理相关手续、联系担保人、签订协议]
    L --> M{是否出国6个月以上}
    M -->|是| N[申请人缴纳保证金3万元]
    N --> O[财务处开立收据]
    O --> P[人力资源处备案] --> Q[学院谈话]
    M -->|否| Q
    Q --> R[国际合作交流处行前培训]
    R --> S[出国（境）]
    S --> T[出国期间工作汇报]
    T --> U[回国]
    U --> V[一个月内持护照、签证等材料到学院和人力资源处报到 《苏州大学公派出国（境）教师回国考核表》]
    V --> W[学院综合办公室考核、报到]
    W --> X[学院负责人审批]
    X --> Y[人力资源处备案]
    Y --> Z[财务处报销费用并退保证金]
    Z --> End(["结束"])