flowchart TD
    Start(["开始"]) --> P1["申请人OA系统申请"]
    P1 --> P2["综合办公室OA行文申请"]
    P2 --> P3["学院分管领导审批"]
    P3 --> Cond1{"判断：处级及以上领导干部？"}
    Cond1 --否--> P4["人力资源处审批"]
    Cond1 --是--> P5["党委组织部审批"] --> P6["分管校领导审批"]
    P4 --> End(["结束"])
    P6 --> End(["结束"])