flowchart TD
    Start(["开始"]) --> Node1("维修完成组织验收，申请人填写《苏州大学工程验收报告书》")
    Node1 --> Node2{"合同金额是否小于1万元（不含）"}
    Node2 -->|是| Node3("资产管理员组织验收")
    Node2 -->|否| Node4{"合同金额是否在1万元（含）-5万元（不含）之间"}
    Node4 -->|是| Node5("资产管理员和归口部门共同组织验收")
    Node4 -->|否| Node6("归口部门组织初步验收")
    Node6 --> Node7("归口部门组织施工单位、对应的行政部门实施正式验收")
    Node5 --> Node8("项目责任人和监理单位（如有）签署竣工验收意见")
    Node7 --> Node8
    Node3 --> Node8
    Node8 --> End(["结束"])