flowchart TD
    Start(["开始"]) --> A[限定性现金捐赠]
    A --> B[在项目中期时提交《苏州大学教育发展基金会资助项目进度表》]
    B --> C[项目负责人审批]
    C --> D[教育发展基金会审核]
    D --> E[提交苏州大学教育发展基金会资助项目结项材料]
    E --> F[项目负责人审批]
    F --> G[教育发展基金会审核]
    Start --> H[实物捐赠]
    H --> I[登记、入库和领用]
    I --> J[备案]
    G --> End(["结束"])
    J --> End(["结束"])