flowchart TD
    Start([开始])
    A[各分管领导牵头制定预算计划（所有的收入和支出）]
    B[综合办公室整理汇总]
    C[预算调整]
    D[系统填报预算]
    E[学院党政联席会议讨论通过]
    F{是否涉及资产}
    G{是否科研教学仪器设备}
    H[实验室与设备管理处审核]
    I[国资处审核]
    J[归口管理部门审核]
    K[国有资产管理处审核]
    L[财务处审核]
    M["“一上”预算审核"]
    N["“二上”审核"]
    O["“一下”数据调整"]
    P[财经领导小组审议]
    Q[校领导审议]
    R["下拨学院预算“二下”"]
    End([结束])

    Start --> A --> B --> C --> D --> E --> F
    F -->|是| G
    F -->|否| J
    G -->|是| H
    G -->|否| I
    H --> K
    I --> K
    J --> K
    K --> L
    L --> M --> N --> O --> P --> Q --> R --> End