flowchart TD
    Start(["开始"])
    End(["结束"])
    A["发起年度固定资产盘点工作"]
    B["组织成立资产清查盘点工作小组，组织实物盘点"]
    C["资产管理员系统记录盘实、盘盈、盘亏的数量、金额，自动生成盘点结果 《资产清查盘点报表》"]
    D["院党政联席会议讨论通过"]
    E["公示待处置资产"]
    F["国有资产管理处审核，汇总盘点情况，账实核对，认定资产损益结果 《固定资产盘点报告》"]
    Start --> A --> B --> C --> D --> E --> F --> End