flowchart TD
    Start(["开始"]) --> P1["经办人提出采购申请"]
    P1 --> P2{"判断预算金额是否在20万元及以上"}
    P2 --是--> P3["预算金额20万元及以上"]
    P2 --否--> P4["预算金额5万元以下"]
    P4 --> P5{"判断是否协议供应商采购"}
    P5 --是--> P6["合同备案"]
    P5 --否--> P7{"判断预算金额是否在5万元以下"}
    P7 --是--> P8["自行选择供应商"] --> P9["审批"] --> P6
    P7 --否--> P10["自行组织3人谈判小组"] --> P9
    P3 --> P11["登录采购平台，填写购置申请表"] --> P12["审批"] --> P13["组织谈判采购或组织竞争性谈判和竞争性磋商等方式采购"] --> P14["形成采购记录和签订采购合同"] --> P6
    P6 --> End(["结束"])