flowchart TD
    Start(["开始"]) --> A[与捐赠方商洽、明确捐赠意向]
    A --> B[捐赠项目可行性论证]
    B --> C[与捐赠方会商捐赠协议内容]
    C --> D[按照捐赠协议规范格式拟定捐赠协议]
    D --> E[学院分管领导审批]
    E --> F[国内合作发展处审核]
    F --> G[校办用印]
    G --> H[合同成立]
    H --> I{是否属于固定资产？}
    I -->|是| J[资产管理员录入苏州大学国有资产管理服务平台]
    I -->|否| K[进入下一步]
    J --> L[取得捐赠物资的发票、入库单、盘点验收]
    K --> L
    L --> M[出具收款通知书、立项表、捐赠协议、实物盘点表等材料]
    M --> N[财务处开具捐赠收据]
    N --> O[财务处入账]
    O --> P[将捐赠收据、盖章后的捐赠协议等材料交付捐赠方]
    P --> Q[每年年终统计汇总实物捐赠情况]
    Q --> End(["结束"])