flowchart TD
    Start(["开始"]) --> A[经办人提出采购申请]
    A --> B{预算金额是否为20万元及以上？}
    B -- 是 --> C[登录采购平台，填写采购申请表]
    B -- 否 --> D{是否协议供应商采购？}
    C --> E[进入实验材料采购系统填写订单]
    D -- 是 --> E
    D -- 否 --> F{预算金额是否为10万元（含）至20万元（不含）？}
    F -- 是 --> G[自行采购]
    F -- 否 --> H{预算金额是否为3万元（含）至10万元（不含）？}
    H -- 是 --> I[自行组织3人谈判小组]
    H -- 否 --> J{预算金额是否为3万元（不含）以下？}
    J -- 是 --> K[小程序上传合同扫描件备案]
    J -- 否 --> L[自行选择供应商]
    L --> M[审批（实验室与物资管理处）]
    M --> N[审批（学院负责人）]
    N --> O[审批（学院项目经费负责人）]
    O --> P[审批（学院经办人）]
    P --> Q[合同备案]
    Q --> R[审批（采购与招标投标管理中心）]
    R --> S[形成采购记录和签订采购合同]
    S --> End(["结束"])